### ISSUE TITLE
Improve bin/chusaku rescue call

### ISSUE THREAD

**Issue by santiagodoldan** [nshki/chusaku#50]
Hello, we were getting different results between running chusaku locally compared with our CI pipeline running chusaku, after some investigation I found that the chusaku binstub is rescuing all errors here https://github.com/nshki/chusaku/blob/main/bin/chusaku#L14-L15, this was hiding an error we have and missing annotations were not blocking our PRs, I'd like to understand the reason of the rescue call there and I'm available to open a PR to improve it if you are ok with it. Thank you so much for this great gem 🙌

**Comment by nshki** [comment]
Hi there! Thank you so much for reporting this and thanks for your kind words! After taking a closer look and testing without the `rescue` in place, I actually am not sure why that's there. I dug through the commit history on the file and wasn't able to find anything immediately obvious either since it's been there since the inception of the gem. It's possible I was running into an unrelated error during R&D.

You are more than welcome to write a pull request to improve on it!

**Comment by santiagodoldan** [comment]
@nshki I'll push a change later today removing the begin; rescue and let's see if the CI passes

**Comment by santiagodoldan** [comment]
Here the PR -> https://github.com/nshki/chusaku/pull/51, please let me know if you want to change something
